### 项目启动端口号
server:
  port: 7777
spring:
  ### 项目应用名
  application:
    name: itrip-hotel-consumer
  main:
    allow-bean-definition-overriding: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000